  cache-algorithm: arc
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:7874
  proxy-server-nameserver:
  - https://223.6.6.6/dns-query
  - https://1.12.12.12/dns-query
  nameserver:
  - 223.5.5.5
  - 114.114.114.114
  nameserver-policy:
    geosite:geolocation-!cn: [tls://dns.google,tls://1.0.0.1]
