  cache-algorithm: arc
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:7874
  nameserver:
  - 223.5.5.5
  - 114.114.114.114
  fallback:
  - 8.8.8.8
  - 8.8.4.4
  - tls://1.0.0.1:853
  - tls://dns.google:853
  nameserver-policy:
  geosite:geolocation-!cn: tls://dns.google
