port: 7890
allow-lan: true
mode: rule
log-level: info
unified-delay: true
global-client-fingerprint: chrome
dns:
  enable: true
  listen: :53
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
  - 223.5.5.5
  - 8.8.8.8
  nameserver:
  - 218.85.157.99
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  fallback:
  - https://1.0.0.1/dns-query
  - tls://dns.google
  - https://dns64.dns.google/dns-query
  nameserver-policy:
    geosite:cn: 218.85.157.99
    geosite:geolocation-!cn: https://dns64.dns.google/dns-query,https://1.0.0.1/dns-query
